/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pw2.h"

extern MYSQL mysql;

#define MAX_ANSWER_SIZE 100

bool_t
query_1_svc(char **argp, char **result, struct svc_req *rqstp)
{
	bool_t retval;
		
	char *answer;
	char *success = "Operation realized with success\0"; 
	char *failure = "Operation failure\0"; 
	
	MYSQL_RES *resultMYSQL;
	MYSQL_FIELD *field;
	MYSQL_ROW row;


	int k=0;
	while( *(*argp+k) != ':') k++;	
	k += 2;

	printf("Action in database -> %s\n",*argp);
	int res = mysql_query(&mysql,*argp+k);			
	if( res != 0 ){
	
		answer = (char *)malloc(sizeof(char)*100);
		sprintf(answer,"%15s",failure);
		
		*result = answer;
		retval = TRUE;

		return retval;
	}
	
	resultMYSQL = mysql_store_result(&mysql);	
	
	int indexSprintF = 0;
	if( resultMYSQL ){

		int numFields = mysql_num_fields(resultMYSQL);
		int numRows = mysql_num_rows(resultMYSQL);
	
		int sizeArray = (numRows+1)*numFields*MAX_ANSWER_SIZE;	
		answer = (char *)malloc(sizeof(char )*(sizeArray));

		int i;
		int j = 0;	
		while( (row = mysql_fetch_row(resultMYSQL))){
		
				for( i=0; i < numFields;i++){

				if( i == 0 ){
					while( field = mysql_fetch_field(resultMYSQL))
						indexSprintF += sprintf(answer+indexSprintF,"%15s\t|",field->name);
					
					indexSprintF += sprintf(answer+indexSprintF,"\n");
				}
				if( row[i] && j < sizeArray ){
					indexSprintF += sprintf(answer+indexSprintF,"%15s\t|",row[i]);
				}
			}		
		}
		mysql_free_result(resultMYSQL);
	}
	else{
		answer = (char *)malloc(sizeof(char)*100);
		sprintf(answer,"%15s",success);
	}

	*result = answer;
	retval = TRUE; 
	
	return retval;
}

int
pw2_query_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}

