
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = bin/client
SERVER = bin/server

TARGETS_SVC.c = src/pw2_svc.c src/pw2_server.c   
TARGETS_CLNT.c = src/pw2_clnt.c src/pw2_client.c   

# Compiler flags 

CPPFLAGS +=
CFLAGS += -g 
LDLIBS += -lpthread 
INCLUDE_DIR = -I include/
COMPILER += gcc

# Targets 
all : $(CLIENT) $(SERVER)

$(CLIENT) : $(OBJECTS_CLNT) 
	$(COMPILER) -o $(CLIENT) $(INCLUDE_DIR) $(TARGETS_CLNT.c) $(LDLIBS) $(CFLAGS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(COMPILER) -o $(SERVER) $(INCLUDE_DIR) $(TARGETS_SVC.c) $(LDLIBS) $(CFLAGS) `mysql_config --libs --cflags`  

clean:
	rm bin/client bin/server
