/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PW2_H_RPCGEN
#define _PW2_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PW2_QUERY_PROG 0x30000001
#define QUERY 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUERY 1
extern  enum clnt_stat query_1(char **, char **, CLIENT *);
extern  bool_t query_1_svc(char **, char **, struct svc_req *);
extern int pw2_query_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUERY 1
extern  enum clnt_stat query_1();
extern  bool_t query_1_svc();
extern int pw2_query_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PW2_H_RPCGEN */
