/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../include/pw2.h"

#include <sys/types.h>
#include <sys/time.h>

CLIENT *clnt;

#define SELECT_ALL "SELECT * FROM name"
#define NUM_MAX_OPERATIONS 5

void
pw2_query_prog_1(char *host)
{
	enum clnt_stat retval_1;

	clnt = clnt_create (host, PW2_QUERY_PROG, QUERY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
}

void generateINSERT(char *machine, char *insert, int age){
	sprintf(insert, "%s: INSERT INTO name(name,age) VALUES('%s%d',%d)", machine, machine, age, age);	
}

void generateDELETE(char *machine, char *delete, int age){
	sprintf(delete, "%s: DELETE FROM name WHERE name='%s%d'", machine, machine, age);
}

void printSelect(double time, char *answer, int op){

	char operation[20];

	switch(op){
		
		case 0:	strcpy(operation,"INSERT ->\0");
				break;
		case 1:	strcpy(operation,"SELECT ->\0");
				break;
		case 2:	strcpy(operation,"DELETE ->\0");
				break;
	}
	
	int size = strlen(answer);
	int i = 0;
	int j;

	printf("\t%14s Time spent: %f\n", operation, time);
	if( op != 1){
		for(j=0;j<13;j++)
			putchar(' ');
	}
	while( i < size){
		if( answer[i] != '|')
			putchar(answer[i]);
		i++;
	}
	printf("\n");
}

double timeCalculation(struct timeval new,struct timeval old){
	
	double init = old.tv_sec*1000000 + old.tv_usec;
	double end  = new.tv_sec*1000000 + new.tv_usec;

	return (end-init)/1000000;
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	pw2_query_prog_1 (host);
	
	srand(time(NULL));

	char insert[100][100];
	char delete[100][100];
	char select[100];

	char *myMachine = getenv("HOSTNAME");

	int i=0;
	for(i=0;i<100;i++ ){
		generateINSERT(myMachine, insert[i],i);
		generateDELETE(myMachine, delete[i],i);
	}
	
	sprintf(select, "%s: %s", myMachine, SELECT_ALL);
	
	int iterations = 0;
	int operation;
	enum clnt_stat retval_1;

	char *result = (char *)malloc(sizeof(char)*1000000);
	char *query = (char *)malloc(sizeof(char)*10000) ;
	
		
	int indexINSERT = rand()%80;
	int indexDELETE = rand()%80;
			
	double times[NUM_MAX_OPERATIONS];
	struct timeval old, new;
	
	printf("            -----------------------------------                  \n");
	while( iterations < NUM_MAX_OPERATIONS) {	

		operation = rand()%50;

		switch(operation){
			case 0:
				strcpy(query,insert[indexINSERT]);
				indexINSERT ++;
				indexINSERT %=100;
				
				gettimeofday(&old,NULL);	
				retval_1 = query_1(&query, &result, clnt);
				gettimeofday(&new,NULL);
				
				if (retval_1 != RPC_SUCCESS) {
					clnt_perror (clnt, "call failed");
				}
				else
					printSelect(timeCalculation(new,old),result,0);

				printf("            -----------------------------------                  \n");
				iterations++;
				break;
			case 1:
				strcpy(query,select);

	
				gettimeofday(&old,NULL);	
				retval_1 = query_1(&query, &result, clnt);
				gettimeofday(&new,NULL);
	
				if (retval_1 != RPC_SUCCESS) {
					clnt_perror (clnt, "call failed");
				}
				else
					printSelect(timeCalculation(new,old),result,1);

				printf("            -----------------------------------                  \n");
				iterations++;
				break;
			case 2:
				strcpy(query,delete[indexDELETE]);
				
				indexDELETE ++;
				indexDELETE %=100;

				gettimeofday(&old,NULL);	
				retval_1 = query_1(&query, &result, clnt);
				gettimeofday(&new,NULL);
	
				if (retval_1 != RPC_SUCCESS) {
					clnt_perror (clnt, "call failed");
				}
				else
					printSelect(timeCalculation(new,old),result,2);
				
				printf("            -----------------------------------                  \n");
				iterations++;
				break;
		}
	
		usleep(1000);
	}

	free(result);
	free(query);
	
	clnt_destroy (clnt);
	exit (0);
}
