/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../include/pw2.h"

#include <sys/types.h>
#include <sys/time.h>

CLIENT *clnt;

#define SELECT_ALL "SELECT * FROM cadastrofunc"
#define NUM_MAX_OPERATIONS 300
#define MAX_SINGLE_OPERATION 100

void
pw2_query_prog_1(char *host)
{
	enum clnt_stat retval_1;

	clnt = clnt_create (host, PW2_QUERY_PROG, QUERY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
}

void setJob(char *job, int *salary, int x) {
	if (x < 30)
	{
		strcpy(job, "Faxineiro\0");
		*salary = 800;
	}
	else if (x < 70)
	{
		strcpy(job, "Tecnico\0");
		*salary = 1800;
		
	}
	else if (x < 95)
	{
		strcpy(job, "Engenheiro\0");
		*salary = 6000;
	}
	else {
		strcpy(job, "Gerente\0");
		*salary = 9000;
	}
}

void generateINSERT(char *machine, char *insert, int age, int x){
	int salary;
	char job[20];
	setJob(job, &salary, x);
	sprintf(insert, "%s: INSERT INTO cadastrofunc(nome,idade,cargo,salario) VALUES('%s%d',%d,'%s',%d)\0", machine, machine, x, age, job, salary);	
}

void generateDELETE(char *machine, char *delete, int x){
	sprintf(delete, "%s: DELETE FROM cadastrofunc WHERE nome='%s%d'\0", machine, machine, x);
}

void printSelect(double time, char *answer, int op){

	char operation[20];

	switch(op){
		
		case 0:	strcpy(operation,"INSERT ->\0");
				break;
		case 1:	strcpy(operation,"SELECT ->\0");
				break;
		case 2:	strcpy(operation,"DELETE ->\0");
				break;
	}
	
	int size = strlen(answer);
	int i = 0;
	int j;

	printf("\t%14s Time spent: %f\n", operation, time);
	if( op != 1){
		for(j=0;j<13;j++)
			putchar(' ');
	}
	while( i < size){
		if( answer[i] != '|')
			putchar(answer[i]);
		i++;
	}
	printf("\n");
}

double timeCalculation(struct timeval new,struct timeval old){
	
	double init = old.tv_sec*1000000 + old.tv_usec;
	double end  = new.tv_sec*1000000 + new.tv_usec;

	return (end-init)/1000000;
}

int
main (int argc, char *argv[])
{
	int i = 0, j = 0, k = 0;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	pw2_query_prog_1 (host);
	
	srand(time(NULL));

	char insert[MAX_SINGLE_OPERATION][150];
	char delete[MAX_SINGLE_OPERATION][150];
	char select[MAX_SINGLE_OPERATION];

	char *myMachine = getenv("HOSTNAME");

	for(i = 0; i < MAX_SINGLE_OPERATION; i++){
		generateINSERT(myMachine, insert[i], 20 + i%40, i);
		generateDELETE(myMachine, delete[i], i);
	}
	
	sprintf(select, "%s: %s\0", myMachine, SELECT_ALL);
	
	int iterations = 0;
	int operation;
	enum clnt_stat retval_1;

	char *result = (char *)malloc(sizeof(char)*1000000);
	char *query = (char *)malloc(sizeof(char)*150) ;
	
		
	int indexINSERT = rand()%80;
	int indexDELETE = rand()%80;
			
	double times[NUM_MAX_OPERATIONS];
	struct timeval old, new;

	printf("            -----------------------------------                  \n");
	
	i = 0;
	j = 0;
	k = 0;

	while( iterations < NUM_MAX_OPERATIONS) {	

		operation = 1;

		switch(operation){
			case 0:
				for (; i < MAX_SINGLE_OPERATION; i++) {
					strcpy(query,insert[indexINSERT]);
					indexINSERT ++;
					indexINSERT %=MAX_SINGLE_OPERATION;
					
					gettimeofday(&old,NULL);	
					retval_1 = query_1(&query, &result, clnt);
					gettimeofday(&new,NULL);
					
					if (retval_1 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					else
						printSelect(timeCalculation(new,old),result,0);

					printf("            -----------------------------------                  \n");
					iterations++;
				}
				break;
			case 1:
				strcpy(query,select);
				
				for (; j < 3*MAX_SINGLE_OPERATION; j++) {
					
					gettimeofday(&old,NULL);	
					retval_1 = query_1(&query, &result, clnt);
					gettimeofday(&new,NULL);
		
					if (retval_1 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					else
						printSelect(timeCalculation(new,old),result,1);

					printf("            -----------------------------------                  \n");
					iterations++;
				}
				break;
			case 2:
				for (; k < MAX_SINGLE_OPERATION; k++) {
					strcpy(query,delete[indexDELETE]);
					
					indexDELETE ++;
					indexDELETE %=MAX_SINGLE_OPERATION;

					gettimeofday(&old,NULL);	
					retval_1 = query_1(&query, &result, clnt);
					gettimeofday(&new,NULL);
		
					if (retval_1 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					else
						printSelect(timeCalculation(new,old),result,2);
					
					printf("            -----------------------------------                  \n");
					iterations++;
				}
				break;
		}
	
	}

	free(result);
	free(query);
	
	clnt_destroy (clnt);
	exit (0);
}
